import { Schema } from './types'

export const property: Schema = {
    pages: [
        {
            content:
                '# قرارداد بیع\nخرید و فروش ملک\n\n## مشخصات طرفین\nفروشنده ملک: ({user_0})\nخریدار:     ({user_1})\n\n## مورد معامله\n\nمیزان دانگ: ({int_1})\nپلاک ثبتی اصلی: ({str_0})\nپلاک ثبتی فرعی: ({str_1})\nبخش ثبتی: ({str_2})\nشهر مورد ثبت ملک: ({str_3})\nکدپستی ملک: ({str_4})\n---\nواقع در آدرس: ({text_0})\nکاربر گرامی شما می توانید موقعیت مکانی ملک خود را بر روی نقشه ثبت نمایید:\n({geo_1})\n\n### وضعیت ملک\n\n({question_0})',
        },
    ],
    fields: {
        user_0: {
            type: 'user',
            value: '',
            uid: 'user_0',
            title: 'Number',
            description: '',
            optinal: false,
        },
        user_1: {
            type: 'user',
            uid: 'user_1',
            value: '',
            title: 'Number',
            description: '',
            optinal: false,
        },
        int_1: {
            type: 'int',
            uid: 'int_1',
            title: 'Number',
            description: '',
            optinal: false,
            max: null,
            min: null,
            value: 0,
        },
        str_0: {
            type: 'str',
            uid: 'str_0',
            title: 'String',
            description: '',
            optinal: false,
            max: null,
            min: null,
            value: '',
        },
        str_1: {
            type: 'str',
            uid: 'str_1',
            title: 'String',
            description: '',
            optinal: false,
            max: null,
            min: null,
            value: '',
        },
        str_2: {
            type: 'str',
            uid: 'str_2',
            title: 'String',
            description: '',
            optinal: false,
            max: null,
            min: null,
            value: '',
        },
        str_3: {
            type: 'str',
            uid: 'str_3',
            title: 'String',
            description: '',
            optinal: false,
            max: null,
            min: null,
            value: '',
        },
        str_4: {
            type: 'str',
            uid: 'str_4',
            title: 'String',
            description: '',
            optinal: false,
            max: 10,
            min: 10,
            value: '',
        },
        text_0: {
            type: 'text',
            uid: 'text_0',
            title: 'Text',
            description: '',
            optinal: false,
            max: null,
            min: null,
            value: '',
        },
        geo_1: {
            type: 'geo',
            uid: 'geo_1',
            title: 'Geo',
            description: '',
            optinal: false,
            value: {
                latitude: 0,
                longitude: 0,
            },
        },
        question_0: {
            type: 'question',
            uid: 'question_0',
            title: 'وضعیت تصرف مالک در ملک فوق',
            description: 'پاسخ سوالات بر پایه صداقت طراحی شده است',
            optinal: false,
            questions: [],
            answers: [],
            value: {},
        },
    },
}
