# register
POST {{ host }}/api/auth/register/
Content-Type: application/json

{
    "phone": "09223334444",
    "first_name": "first name test",
    "last_name": "last name test",
    "birth_date": [1370, 12, 12],
    "national_id": "1212121212",
    "postal_code": "1111111111",
    "address": "strkad;kal;sdk",
    "email": "gg@ez.org"
}

###

# request a login
POST {{ host }}/api/auth/login/
Content-Type: application/json

{
    "phone": "09223334444"
}

###

# verify login
# @name login
POST {{ host }}/api/auth/verify/
Content-Type: application/json

{
    "phone": "09223334444",
    "code": "93239"
}

###

@token = {{ login.response.body.token }}

# get user info
GET {{ host }}/api/user/update/
Authorization: user {{ token }}


### 

POST {{ host }}/api/user/delete/
Content-Type: application/json
Authorization: user {{ token }}

###

POST {{ host }}/api/user/delete_verify/
Authorization: user {{ token }}
Content-Type: application/json

{
    "code": "50496"
}